name: Deployer release
env:
  REGISTRY_IMAGE: ghcr.io/prokleta-kuja/deployer
on:
  workflow_dispatch:
  push:
    branches:
      - "main"

jobs:
  build:
    name: Build and push image
    runs-on: ubuntu-latest
    steps:
      - name: Generate env variables
        run: |
          echo "DATE=$(date +'%Y-%m-%d')" >> ${GITHUB_ENV}
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: true
          tags: |
            ${{ env.REGISTRY_IMAGE }}:latest
            ${{ env.REGISTRY_IMAGE }}:${{ env.DATE }}
            ${{ env.REGISTRY_IMAGE }}:${{ github.RUN_NUMBER }}
